name: CI/CD
on: push
jobs:
  build:
    name: CI&CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '18.x'

      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        run: pnpm i

      - name: Build Packages
        run: pnpm run build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install faraday-retry gem
        run: gem install faraday-retry

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4